version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pagila_master
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/01_pagila_schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sync-net

  mysql:
    image: mysql:8
    container_name: pagila_slave
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sync-net

  backend:
    build: ./backend
    container_name: sync_backend
    environment:
      NODE_ENV: development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mysql
    networks:
      - sync-net

  frontend:
    build: ./frontend
    container_name: sync_frontend
    ports:
      - "5000:80"
    depends_on:
      - backend
    networks:
      - sync-net

networks:
  sync-net:
    driver: bridge